@GameHub.WebAPI_HostAddress = http://localhost:5192

###
POST {{GameHub.WebAPI_HostAddress}}/api/identity/auth
Content-Type: application/json
{
  "email": "juan.canseco@gmail.com  ",
  "password": "juan1234"
}