<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MassTransit" Version="9.0.1" />
    <PackageReference Include="MediatR" Version="12.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.13" />
    <PackageReference Include="System.Linq.AsyncEnumerable" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameHub.Contracts\GameHub.Contracts.csproj" />
    <ProjectReference Include="..\GameHub.Domain\GameHub.Domain.csproj" />
    <ProjectReference Include="..\GameHub.EventBus.Contracts\GameHub.EventBus.Contracts.csproj" />
  </ItemGroup>

</Project>
