using GameHub.Application.Abstractions.Observability;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi.Models;

namespace GameHub.Web.API.OpenApi;

internal static class OpenApiServiceCollectionExtensions
{
    private const string BearerScheme = "Bearer";

    internal static IServiceCollection AddGameHubOpenApi(this IServiceCollection services)
    {
        services.AddOpenApi(options =>
        {
            options.AddDocumentTransformer((document, _, _) =>
            {
                document.Info = new OpenApiInfo
                {
                    Title = "GameHub API",
                    Version = "v1",
                    Description =
                        "HTTP API for GameHub authentication, channels, and chats. " +
                        "Protected operations require a GameHub JWT bearer token."
                };

                document.Components ??= new OpenApiComponents();
                document.Components.SecuritySchemes[BearerScheme] = new OpenApiSecurityScheme
                {
                    Type = SecuritySchemeType.Http,
                    Scheme = "bearer",
                    BearerFormat = "JWT",
                    Description = "The JWT returned by POST /api/identity/auth."
                };

                return Task.CompletedTask;
            });

            options.AddOperationTransformer((operation, context, _) =>
            {
                operation.Parameters ??= [];
                operation.Parameters.Add(new OpenApiParameter
                {
                    Name = CorrelationIdConstants.HeaderName,
                    In = ParameterLocation.Header,
                    Required = false,
                    Description =
                        "Optional request correlation identifier. Use 1-64 ASCII letters, digits, '-', '_', or '.'. " +
                        "The API returns the accepted or generated value in the same response header.",
                    Schema = new OpenApiSchema
                    {
                        Type = "string",
                        MaxLength = CorrelationIdConstants.MaxLength,
                        Pattern = "^[A-Za-z0-9._-]+$"
                    }
                });

                foreach (var response in operation.Responses.Values)
                {
                    response.Headers ??= new Dictionary<string, OpenApiHeader>();
                    response.Headers.TryAdd(
                        CorrelationIdConstants.HeaderName,
                        CreateCorrelationIdHeader());
                }

                var metadata = context.Description.ActionDescriptor.EndpointMetadata;
                var allowsAnonymous = metadata.OfType<IAllowAnonymous>().Any();
                var requiresAuthorization = metadata.OfType<IAuthorizeData>().Any();

                if (!allowsAnonymous && requiresAuthorization)
                {
                    operation.Security =
                    [
                        new OpenApiSecurityRequirement
                        {
                            [new OpenApiSecurityScheme
                            {
                                Reference = new OpenApiReference
                                {
                                    Type = ReferenceType.SecurityScheme,
                                    Id = BearerScheme
                                }
                            }] = []
                        }
                    ];

                    operation.Responses.TryAdd("401", new OpenApiResponse
                    {
                        Description = "The bearer token is missing, invalid, or expired."
                    });
                    operation.Responses.TryAdd("403", new OpenApiResponse
                    {
                        Description = "The authenticated caller is not allowed to perform this operation."
                    });

                    foreach (var responseCode in new[] { "401", "403" })
                    {
                        operation.Responses[responseCode].Headers = new Dictionary<string, OpenApiHeader>
                        {
                            [CorrelationIdConstants.HeaderName] = CreateCorrelationIdHeader()
                        };
                    }
                }

                return Task.CompletedTask;
            });
        });

        return services;
    }

    private static OpenApiHeader CreateCorrelationIdHeader() => new()
    {
        Required = true,
        Description = "The request correlation identifier accepted or generated by the API.",
        Schema = new OpenApiSchema { Type = "string" }
    };

}
