<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StartupObject>GameHub.Web.API.Program</StartupObject>
    <AssemblyName>GameHub.Web.API</AssemblyName>
    <AssemblyTitle>GameHub.Web.API</AssemblyTitle>
    <RootNamespace>GameHub.Web.API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Carter" Version="8.2.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.13">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GameHub.Infrastructure\GameHub.Infrastructure.csproj" />
  </ItemGroup>

</Project>
